### ISSUE TITLE
배치 전송

### ISSUE THREAD

**Issue by minkyu-yi** [nhnent/tui.component.file-uploader#2]

**Comment by icebelle** [comment]
Works Mobile - https://www.worksmobile.com
--------------------------------------------
류진경(icebelle@nhnent.com) 님은 현재 부재중입니다.</br>
보내신 메일 <[tui.component.file-uploader] 배치 전송 (#2)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
류진경(icebelle@nhnent.com) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-12-29 09:30 ~ 2015-12-30 18:30 GMT +09:00]<br>개인 휴가로 이틀간 부재입니다. 메일은 출근 후 확인하여 회신 드리겠습니다. 급한 용무는 핸드폰으로 연락주세요.
--------------------------------------------

**Comment by minhyeong-kim** [comment]
Works Mobile - https://www.worksmobile.com
--------------------------------------------
김민형(minhyeong.kim@nhnent...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [tui.component.file-uploader] 배치 전송 (#2)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김민형(minhyeong.kim@nhnent...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-12-29 09:30 ~ 2015-12-30 18:30 GMT +09:00]<br>개인사유로 휴가입니다. 급한 용무는 전화 부탁드립니다.
--------------------------------------------

**Comment by icebelle** [comment]
Works Mobile - https://www.worksmobile.com
--------------------------------------------
류진경(icebelle@nhnent.com) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [tui.component.file-uploader] 배치 전송 (#2)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
류진경(icebelle@nhnent.com) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-12-29 09:30 ~ 2015-12-30 18:30 GMT +09:00]<br>개인 휴가로 이틀간 부재입니다. 메일은 출근 후 확인하여 회신 드리겠습니다. 급한 용무는 핸드폰으로 연락주세요.
--------------------------------------------
